---
- name: Install the docToolchain
  hosts: all
  become: yes
  vars:
    dest_dir: /docToolchain-master
    resources: /docToolchain-master/resources
    git: true

  tasks:
    - name: Set timezone to Hardware Clock
      timezone:
        name: America/New_York

    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Required Packages
      apt: name={{ item }} state=latest
      with_items:
        - unzip
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
        - pandoc
        - git

    - name: Clone docToolchain
      git:
        repo: https://github.com/docToolchain/docToolchain.git
        dest: "{{ dest_dir }}"
      when: git

    - name: Set Permissions on {{ dest_dir }}
      file:
        path: "{{ dest_dir }}"
        owner: vagrant
        group: vagrant
        recurse: yes

    - name: add doctoolchain to path
      copy:
        dest: /etc/profile.d/doctool-path.sh
        content: 'PATH=$PATH:{{ dest_dir }}/bin'

## Need to add pdf-fontsdir to scripts/AsciiDocBasics.gradle
##             'pdf-fontsdir': "${docDir}/pdfTheme/fonts",
    - name: Add pdf-fontsdir to AsciidocBasics.gradle
      patch:
        src: AsciiDocBasics.patch
        dest: "{{ dest_dir }}/scripts/AsciiDocBasics.gradle"
