---
- name: Install the docToolchain
  hosts: all
  become: yes
  vars: 
    dest_dir: /docToolchain-master
    resources: /docToolchain-master/resources

  tasks:
    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Required Packages
      apt: name={{ item }} state=latest
      with_items:
        - unzip
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
        - pandoc

## Need to fix permissions on /docToolchain-master directory so vagrant can write to it.  
    - name: Get docToolchain
      unarchive: 
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        creates: '{{ item.creates }}'
        owner: vagrant
        remote_src: yes
      with_items: 
        - { src: 'https://github.com/docToolchain/docToolchain/archive/master.zip', dest: '/', creates: '/docToolchain-master' }
        - { src: 'https://github.com/hakimel/reveal.js/archive/tags/3.3.0.zip', dest: '/docToolchain-master/resources/', creates: '{{ resources }}/reveal.js-tags-3.3.0' }
        - { src: 'https://github.com/asciidoctor/asciidoctor-reveal.js/archive/9667f5c.zip', dest: '/docToolchain-master/resources/', creates: '{{ resources }}/asciidoctor-reveal.js-9667f5c5d926b3be48361d6d6413d3896954894c' }
    - name: Replace reveal files 
      synchronize: 
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        recursive: yes
        delete: yes
      delegate_to: "{{ inventory_hostname }}"
      with_items: 
        - {src: '{{ resources }}/reveal.js-tags-3.3.0',  dest: '{{ resources }}/reveal.js' }
        - {src: '{{ resources }}/asciidoctor-reveal.js-9667f5c5d926b3be48361d6d6413d3896954894c',  dest: '{{ resources }}/asciidoctor-reveal.js' }

## Need to add pdf-fontsdir to scripts/AsciiDocBasics.gradle
##             'pdf-fontsdir': "${docDir}/pdfTheme/fonts",

